#!/bin/bash
#icewm-session -s &

sleep 1 &&
xfce4-power-manager &

sleep 1 &&
gvolwheel &

sleep 1 &&
redshift &

#polybar -c ~/.config/polybar/icewm-bar.ini -r &

gvolwheel &

xmodmap ~/.Xmodmap &

sleep 1 &&
ibus-daemon -rxd &

xfce4-notifyd &

#icewmbg -i /usr/share/backgrounds/julia.jpg --center=1

#/home/zkitty/.fehbg &

xcompmgr -r 9.8 -o 0.61 -l -13.8 -t -14.5 -I 0.017 -O 0.02 -D 6.0 -c -C -f -F -n &

conky &

sleep 1 &&
nm-applet &

rescrobbled &

sleep 1 &&
copyq &
